### ISSUE TITLE
add coral associates as occurrences

### ISSUE THREAD

**Issue by sformel-usgs** [kylieh10/gomx_sediment_macrofauna#1]
We included the corals next to the cores as `associatedTaxa` but didn't create occurrenceIDs for these.  @kylieh10 please do this when you have a moment. We may also want to reconsider `associatedTaxa` as `associatedOccurrences`.

**Comment by kylieh10** [comment]
We may need to possibly unnest the event table, since it is one coral seen at each station-level event.

**Comment by sformel-usgs** [comment]
We elected to revert these to `associatedTaxa` with Amanda and Jill's approval
